events {} 
 
http { 
  server { 
    listen 80;  # Слушать на порту 80 
 
    # Запросы на / → Frontend контейнер 
    location / { 
      proxy_pass http://frontend:3000; 
    } 
 
    # Запросы на /api → Backend контейнер 
    location /api { 
      proxy_pass http://backend:5000; 
    } 
  } 
} 
